version: '3.5'

networks:
  localdev:
    name: localdev
    
services:
  tasklauncher.api:
    image: tasklauncher.api
    container_name: tasklauncher.api
    build:
        context: .
        dockerfile: TaskLauncher.Api/Dockerfile
    restart: always
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    depends_on:
      - db-server
    networks:
      - localdev
        
  tasklauncher.webapp.server:
    image: tasklauncher.webapp.server
    container_name: tasklauncher.webapp.server
    build:
        context: .
        dockerfile: TaskLauncher.WebApp/Server/Dockerfile
    restart: always
    ports:
      - "7000:80"
      - "7001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    depends_on:
      - db-server
    networks:
      - localdev

  db-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass1234
      - MSSQL_TCP_PORT=1433
    ports:
      - "1400:1433"
    networks:
      - localdev

  tasklauncher.containerlauncher:
    image: tasklauncher.containerlauncher
    container_name: tasklauncher.containerlauncher
    build:
      context: .
      dockerfile: TaskLauncher.ContainerLauncher/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - tasklauncher.api
    networks:
      - localdev