version: '3.5'

services:
  tasklauncher.worker:
    image: wutshot/worker:latest
    container_name: tasklauncher.worker
    environment:
      - ServiceAddresses__WebApiAddress=https://auth0blazorwasmserverapp.azurewebsites.net
      - ServiceAddresses__HubAddress=https://auth0blazorwasmserverapp.azurewebsites.net/WorkerHub
      - TaskLauncherConfig__Source=bp_worker-vol
      - TaskLauncherConfig__ImageName=wutshot/testimage
      - Auth0ApiConfiguration__Domain=bptasklauncher-test.eu.auth0.com
      - Auth0ApiConfiguration__ClientId=H00nU96LrTvYskDdrsVgfReFmwk8ICbd
      - Auth0ApiConfiguration__ClientSecret=pIRWtKz0eAo34XO-W9sUwuTyeF8Gt6twVcAlNmbt_ZC9ZEqeUHQvqiIkyODWoUlC
      - Auth0ApiConfiguration__Audience=https://bptasklauncherapi-test.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - worker-vol:/app/tmp

volumes:
  worker-vol: